# Generated by Django 4.2.5 on 2024-03-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
