# Generated by Django 4.2.5 on 2024-03-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='img',
            field=models.ImageField(null=True, upload_to='reviewratingpfp'),
        ),
    ]
