# Generated by Django 4.2.5 on 2024-03-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='img',
            new_name='profile_picture',
        ),
    ]
