# Generated by Django 4.2.5 on 2023-09-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_product_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
