# Generated by Django 4.2.5 on 2023-09-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_delete_product_delete_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
    ]
