# Generated by Django 4.2.5 on 2023-09-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
