# Generated by Django 4.2.5 on 2023-09-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cartitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
    ]
