# Generated by Django 4.2.5 on 2024-03-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ice',
            name='city_state',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ice',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ice',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ice',
            name='full_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ice',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ice',
            name='phone',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
