# Generated by Django 4.2.5 on 2024-03-26 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_ice_city_state_ice_country_ice_date_ice_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
