# Generated by Django 4.2.5 on 2024-03-26 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_ice_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ice',
            new_name='CashOnDelivery',
        ),
    ]
