# Generated by Django 4.2.5 on 2024-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_ice_cashondelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashondelivery',
            options={'verbose_name_plural': 'Cash On Delivery'},
        ),
        migrations.AddField(
            model_name='cashondelivery',
            name='is_recievedd',
            field=models.CharField(choices=[('on_delivery', 'On Delivery'), ('received', 'Received'), ('pending', 'Pending')], max_length=150, null=True),
        ),
    ]
