# Generated by Django 4.2.5 on 2024-03-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cashondelivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashondelivery',
            name='is_recievedd',
            field=models.CharField(choices=[('on_delivery', 'On Delivery'), ('received', 'Received'), ('pending', 'Pending')], default='pending', max_length=150, null=True),
        ),
    ]
