# Generated by Django 4.2.5 on 2024-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cashondelivery_is_recievedd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashondelivery',
            name='is_recievedd',
            field=models.CharField(choices=[('on_delivery', 'On Delivery'), ('received', 'Received'), ('pending', 'Pending')], default='received', max_length=150, null=True),
        ),
    ]
