# Generated by Django 4.2.5 on 2024-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_cashondelivery_is_recievedd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_delivery', 'On Delivery'), ('received', 'Received'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='New', max_length=150),
        ),
    ]
